/* ==============================================
   data.js
   きもちチェックのデータファイル
   ・BUBBLES : 特効薬バブルの一覧
   ・MD      : きもちごとの見出し・説明・アイコン設定
   ============================================== */


/* ── バブルのジャンル別カラー定義 ── */
const BC = {
  発散:       {c:"#FBEAF0", tc:"#72243E"},  /* ピンク系 */
  落ち着き:   {c:"#E1F5EE", tc:"#085041"},  /* 緑系 */
  気分転換:   {c:"#FAEEDA", tc:"#633806"},  /* 黄色系 */
  人とつながる:{c:"#E6F1FB", tc:"#0C447C"},  /* 青系 */
  からだ:     {c:"#EAF3DE", tc:"#27500A"},  /* 薄緑系 */
  表現:       {c:"#EEEDFE", tc:"#3C3489"},  /* 紫系 */
};


/* ── 全特効薬バブルのデータ ──
   フィールドの説明：
     t    : 表示テキスト
     g    : ジャンル（色の種類）
     img  : 画像ファイル名（acts/フォルダ内）
     desc : 詳細画面に表示する解説文（50文字程度）
     tags : スコアリング用タグ
   ============================================== */
const BUBBLES = [
  {t:"そとでジャンプしてみる",
   g:"発散",
   img:"act-jump-happy.png",
   desc:"たかく ジャンプして、もやもや エネルギーを そとに だしちゃおう！",
   tags:{mood:["angry","happy"], energy:"high", social:["alone","neutral","social"], body:"fine", wish:"play"}},
  {t:"そのばではしってみる",
   g:"発散",
   img:"act-jump-happy.png",
   desc:"そのばで こばしりするだけでも、からだが すっきりしちゃうかもね。",
   tags:{mood:["angry","happy"], energy:["high","mid"], social:["alone","neutral","social"], body:"fine", wish:"play"}},
  {t:"かみをビリビリやぶいてみる",
   g:"発散",
   img:"act-tear-paper.png",
   desc:"やぶってもいい かみを ビリビリ やぶくと、きもちが すっきりするのさ！",
   tags:{mood:"angry", energy:["high","mid"], social:["alone","neutral"], body:["fine","heart"], wish:"any"}},
  {t:"まくらにさけんでみる",
   g:"発散",
   img:"act-scream-in-pillow.png",
   desc:"まくらに かおを うずめて、「わーっ！」と おおごえで さけんでみよう。",
   tags:{mood:"angry", energy:["high","mid"], social:["alone","neutral"], body:["fine","breath","heart"], wish:"any"}},
  {t:"ぎゅーっててをにぎってみる",
   g:"発散",
   img:"act-hold-hand.png",
   desc:"こぶしを ギュッと にぎって、 パワーを ためよう。",
   tags:{mood:["angry","anxious"], energy:"any", social:"any", body:"heart", wish:"any"}},
  {t:"おもいきりのびをしてみる",
   g:"発散",
   img:"act-stretch.png",
   desc:"うえに おおきく のびをして、ゆ～っくり いきを はきだす。",
   tags:{mood:["angry","anxious","sad"], energy:"any", social:"any", body:["breath","fine"], wish:"any"}},
  {t:"おもいっきりわらってみる",
   g:"発散",
   img:"act-laugh-hardly.png",
   desc:"たのしいことを おもいだして、こえにだして わらってみるのだ！ ガハハハハ！",
   tags:{mood:"happy", energy:["high","mid"], social:["alone","social"], body:"fine", wish:"play"}},
  {t:"トイレでゆっくりいきをはいてみる",
   g:"落ち着き",
   img:"act-deepbreath-in-bathroom.png",
   desc:"おちつける トイレへ いって、いきを「はー」って だしてみる。",
   tags:{mood:["angry","anxious"], energy:"any", social:"any", body:["breath","heart"], wish:"any"}},
  {t:"ゆっくりしんこきゅうしてみる",
   g:"落ち着き",
   img:"act-deepbreath.png",
   desc:"むねに てをあてて、ふくらませながら ふかーくすって はいてみるのだ。",
   tags:{mood:["anxious","angry","sad"], energy:"any", social:"any", body:["breath","heart"], wish:"any"}},
  {t:"しんこきゅうを3かいしてみる",
   g:"落ち着き",
   img:"act-deepbreath.png",
   desc:"ゆっくり 3かい しんこきゅう するだけで、きもちが おちつくよ。",
   tags:{mood:["anxious","angry","sad"], energy:"any", social:"any", body:["heart","breath"], wish:"any"}},
  {t:"4びょうすって8びょうはいてみる",
   g:"落ち着き",
   img:"act-deepbreath.png",
   desc:"4びょうかけて すって、8びょうかけて ゆっくり はいてみよう。",
   tags:{mood:"anxious", energy:"any", social:"any", body:["heart","breath"], wish:"any"}},
  {t:"めをとじて10かぞえてみる",
   g:"落ち着き",
   img:"act-closeeyes-char.png",
   desc:"めを とじて、ゆっくり 10まで かぞえながら おちつこう。",
   tags:{mood:["anxious","angry"], energy:"any", social:"any", body:["heart","breath"], wish:"any"}},
  {t:"すわってめをとじてみる",
   g:"落ち着き",
   img:"act-closeeyes-char.png",
   desc:"らくな しせいで すわって、めを とじて しばらく やすむのも いいよね。",
   tags:{mood:["sad","anxious"], energy:["low","verylow"], social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"しばらくひとりでいてみる",
   g:"落ち着き",
   img:"act-laydown.png",
   desc:"しずかな ばしょで、ひとりぼっちの じかんを つくってみよう。",
   tags:{mood:["angry","sad","anxious"], energy:["low","mid"], social:"alone", body:["fine","breath"], wish:"nothing"}},
  {t:"すきなばしょですわってみる",
   g:"落ち着き",
   img:"act-sitting-fav-place.png",
   desc:"きみが いちばん おちつける ばしょは どこかな？ そこにいって じっとしてみよう。",
   tags:{mood:["anxious","sad"], energy:["low","mid"], social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"めをとじてやすんでみる",
   g:"落ち着き",
   img:"act-laydown-rest.png",
   desc:"めを とじて、からだの ちからを ぬいて ゆっくり やすもうぜ。",
   tags:{mood:["sad","anxious"], energy:["verylow","low"], social:"any", body:["fine","bad"], wish:"sleep"}},
  {t:"きょうはゆっくりやすんでみる",
   g:"落ち着き",
   img:"act-laydown-rest.png",
   desc:"きょうは むりせず、のんびり すごして みるってのはどう？",
   tags:{mood:["sad","anxious"], energy:["verylow","low"], social:"any", body:["fine","bad"], wish:"sleep"}},
  {t:"ゆっくりあるいてみる",
   g:"落ち着き",
   img:"act-walk-with-adult.png",
   desc:"いそがず ゆっくり あるいて、あしのうらを かんじてみるのさ。なめくじさんより おそくなれるかい？",
   tags:{mood:["sad","anxious"], energy:["low","mid"], social:["alone","neutral","social"], body:["fine","bad","breath"], wish:["nothing","sleep"]}},
  {t:"そとをおさんぽしてみる",
   g:"落ち着き",
   img:"act-walk-with-adult.png",
   desc:"そとの くうきを すいながら、のんびり おさんぽして みない？",
   tags:{mood:["happy","sad"], energy:["high","mid"], social:["alone","neutral","social"], body:"fine", wish:"play"}},
  {t:"5ふんだけそとをあるいてみる",
   g:"落ち着き",
   img:"act-run-plain.png",
   desc:"5ふんだけ そとに でて、うえを むいて あるいてみよう。...でも、ころばないでね。",
   tags:{mood:["sad","angry","anxious"], energy:"mid", social:["alone","neutral","social"], body:"fine", wish:"nothing"}},
  {t:"そとではしってみる",
   g:"落ち着き",
   img:"act-run-plain.png",
   desc:"そとで すこし はしってみると、きもちが スッキリするかも！！",
   tags:{mood:["happy","angry"], energy:"high", social:["alone","neutral","social"], body:"fine", wish:"play"}},
  {t:"すきなうたをきいてみる",
   g:"気分転換",
   img:"act-listen-music.png",
   desc:"すきな きょくを きいてみよう。ちなみに わたしの マイブームは、『さっちゃん』。",
   tags:{mood:["sad","anxious","angry"], energy:["low","mid"], social:["alone","neutral"], body:["fine","bad","breath"], wish:["nothing","sleep"]}},
  {t:"すきなどうがをみてみる",
   g:"気分転換",
   img:"act-using-tablet.png",
   desc:"すきな どうがや アニメを みて、きぶんを かえちゃうのさ。",
   tags:{mood:["sad","anxious"], energy:["low","mid"], social:["alone","neutral"], body:["fine","bad"], wish:"nothing"}},
  {t:"すきなうたにあわせておどってみる",
   g:"気分転換",
   img:"act-dance.png",
   desc:"すきな きょくに あわせて、からだを うごかして たのしもう！ ずんちゃっちゃ ずんちゃっちゃ。",
   tags:{mood:"happy", energy:"high", social:["alone","social"], body:"fine", wish:"play"}},
  {t:"すきなほんをよんでみる",
   g:"気分転換",
   img:"act-read-book.png",
   desc:"すきな ほんを ひらいて、ものがたりの せかいへ レッツらゴー！",
   tags:{mood:["sad","anxious"], energy:["low","mid"], social:["alone","neutral"], body:["fine","bad"], wish:"nothing"}},
  {t:"すきなキャラクターをながめてみる",
   g:"気分転換",
   img:"act-play-with-dolls.png",
   desc:"すきな キャラクターの グッズや えを、じっくり ながめてみよう。",
   tags:{mood:["sad","anxious"], energy:["low","mid"], social:["alone","neutral"], body:["fine","bad"], wish:"nothing"}},
  {t:"すきなキャラクターのえをかいてみる",
   g:"気分転換",
   img:"act-paint.png",
   desc:"すきな キャラクターの えを、じゆうに かいてみるのさ。",
   tags:{mood:["happy","sad"], energy:["high","mid"], social:"alone", body:"fine", wish:"play"}},
  {t:"あたらしいあそびをためしてみる",
   g:"気分転換",
   img:"act-play-with-friends.png",
   desc:"やったことがない あそびを、ひとつ ためしてみよう。ワクワク！",
   tags:{mood:"happy", energy:["high","mid"], social:["alone","neutral","social"], body:"fine", wish:"play"}},
  {t:"すきなあそびをしてみてみる",
   g:"気分転換",
   img:"act-play-with-friends.png",
   desc:"いちばん すきな あそびで、おもいきり たのしんじゃう！！？！",
   tags:{mood:"happy", energy:["high","mid"], social:["alone","neutral","social"], body:"fine", wish:"play"}},
  {t:"おりがみをおってみる",
   g:"気分転換",
   img:"act-origami.png",
   desc:"おりがみを おることに しゅうちゅうすると、きもちが おちつくよ。",
   tags:{mood:["sad","anxious"], energy:["low","mid"], social:["alone","neutral"], body:["fine","bad"], wish:"nothing"}},
  {t:"ちいさなかたづけをしてみる",
   g:"気分転換",
   img:"act-cleanup.png",
   desc:"みの まわりを ちょびっと かたづけると、あたまも きもちも ちょびっと スッキリ！",
   tags:{mood:["sad","angry"], energy:["mid","low"], social:["alone","neutral"], body:"fine", wish:"nothing"}},
  {t:"たいようをあびてみる",
   g:"気分転換",
   img:"act-sunbathing.png",
   desc:"そとに でて、たいようの ひかりを からだじゅうで あびてみよう。くもってたら ごめんね。",
   tags:{mood:["sad","anxious"], energy:["low","mid"], social:["alone","neutral","social"], body:["fine","bad","breath"], wish:["nothing","sleep"]}},
  {t:"そとのそらをみあげてみる",
   g:"気分転換",
   img:"act-looking-at-clouds.png",
   desc:"そらを みあげて、くもを ながめてみるのも いいね。くもがひとつもなかったら...... それもステキ。",
   tags:{mood:["anxious","sad"], energy:["low","mid"], social:["alone","neutral","social"], body:["breath","fine"], wish:["nothing","sleep"]}},
  {t:"しんらいできるひとにはなしてみる",
   g:"人とつながる",
   img:"act-talk-concern.png",
   desc:"いまのきもちを、だれか しんらいできるひとに はなしてみる。",
   tags:{mood:["sad","anxious","angry"], energy:["low","mid","verylow"], social:"social", body:["fine","heart","bad"], wish:"talk"}},
  {t:"せんせいにはなしかけてみる",
   g:"人とつながる",
   img:"act-talk-to-adult-02.png",
   desc:"しんらいできる せんせいに、「ちょっと いい？ かわいいかわいい ぼくちゃんが はなしたいこと あるんだけど」と、いってみる。",
   tags:{mood:["sad","anxious"], energy:["low","mid","verylow"], social:"social", body:["fine","bad"], wish:"talk"}},
  {t:"だれかにそばにいてもらう",
   g:"人とつながる",
   img:"act-stay-with-adult.png",
   desc:"だれかに ちかくに いてもらうだけで あんしんしちゃうかも。",
   tags:{mood:["sad","anxious"], energy:["verylow","low"], social:"social", body:["fine","bad","heart"], wish:["nothing","sleep"]}},
  {t:"やさしいひとのそばにいてみる",
   g:"人とつながる",
   img:"act-stay-with-adult.png",
   desc:"やさしい ひとの ちかくに いるだけで、きもちが らくに なるよ。",
   tags:{mood:["sad","anxious"], energy:["verylow","low"], social:"social", body:["fine","bad","heart"], wish:["nothing","sleep"]}},
  {t:"おともだちにはなしかけてみる",
   g:"人とつながる",
   img:"act-talk-with-friend.png",
   desc:"ともだちに、「さいきん どう？」と はなしかけてみるのさ。",
   tags:{mood:["sad","anxious","angry"], energy:["low","mid"], social:"social", body:["fine","heart"], wish:"talk"}},
  {t:"ともだちをさそってみる",
   g:"人とつながる",
   img:"act-talk-with-friend.png",
   desc:"ともだちを、「いっしょに へのへのもへじ かこ！」と さそってみよう。",
   tags:{mood:"happy", energy:["high","mid"], social:"social", body:"fine", wish:"play"}},
  {t:"おともだちとわらいあってみる",
   g:"人とつながる",
   img:"act-talk-with-friend.png",
   desc:"ともだちと いっしょに、わらえる ことをして たのしもう。",
   tags:{mood:"happy", energy:["high","mid"], social:"social", body:"fine", wish:"play"}},
  {t:"だれかにえがおをむけてみる",
   g:"人とつながる",
   img:"act-laugh.png",
   desc:"あった ひとに えがおを むけてみて。じぶんも きもちが よくなるよ。",
   tags:{mood:"happy", energy:["high","mid"], social:"social", body:"fine", wish:["play","talk"]}},
  {t:"ともだちにありがとうといってみる",
   g:"人とつながる",
   img:"act-talk-with-friend.png",
   desc:"ともだちに 「ありがとう」を つたえると、ふたりとも ハッピー！",
   tags:{mood:"happy", energy:["high","mid"], social:"social", body:"fine", wish:"talk"}},
  {t:"たのしいきもちをだれかにつたえてみる",
   g:"人とつながる",
   img:"act-talk-to-adult-02.png",
   desc:"「たのしかった！」を だれかに はなすと、もっともっと うれしく なるよ。",
   tags:{mood:"happy", energy:["high","mid"], social:"social", body:"fine", wish:"talk"}},
  {t:"だれかをわらわせてみる",
   g:"人とつながる",
   img:"act-talk-with-friend.png",
   desc:"おもしろいことを はなして、だれかを わらわせて みないかい？",
   tags:{mood:"happy", energy:["high","mid"], social:"social", body:"fine", wish:"talk"}},
  {t:"おともだちのそばにいてみる",
   g:"人とつながる",
   img:"act-play-with-friends.png",
   desc:"おともだちの ちかくに いるだけで、しんぱいが やわらぐかもね。",
   tags:{mood:["anxious","sad"], energy:["low","mid"], social:"social", body:["fine","heart","bad"], wish:["nothing","talk"]}},
  {t:"みずをゴクっとのんでみる",
   g:"からだ",
   img:"act-drink.png",
   desc:"のみものを ひとくち ゴクッと のんでみて、おちつこう。",
   tags:{mood:"angry", energy:"any", social:"any", body:["fine","heart","bad"], wish:"any"}},
  {t:"つめたいみずをのんでみる",
   g:"からだ",
   img:"act-drink.png",
   desc:"つめたい みずを ゆっくり のんで、からだも こころも クールダウン。",
   tags:{mood:"angry", energy:"any", social:"any", body:["fine","heart","bad"], wish:"any"}},
  {t:"みずをゆっくりのんでみる",
   g:"からだ",
   img:"act-drink.png",
   desc:"みずを ゆっくり すこしずつ のんで、いきを ととのえて みよう。",
   tags:{mood:"anxious", energy:"any", social:"any", body:["heart","breath","bad"], wish:"any"}},
  {t:"てをあらってすっきりしてみる",
   g:"からだ",
   img:"act-sunbathing.png",
   desc:"てを ていねいに あらって、きもちを すっきり させてみよう。",
   tags:{mood:["sad","angry"], energy:"any", social:"any", body:["bad","fine"], wish:"any"}},
  {t:"あしのうらをかんじてみる",
   g:"からだ",
   img:"act-sitting-fav-chair.png",
   desc:"あしのうらに ふれているものを、しっかり かんじて みて。",
   tags:{mood:"anxious", energy:"any", social:"any", body:["heart","breath"], wish:"any"}},
  {t:"てのひらをひざにおいてみる",
   g:"からだ",
   img:"act-closeeyes-char.png",
   desc:"てのひらを ひざに おいて、こきゅうだけに しゅうちゅう しよう。",
   tags:{mood:"anxious", energy:"any", social:"any", body:["heart","breath"], wish:"any"}},
  {t:"みえるものを5つさがしてみる",
   g:"からだ",
   img:"act-thinking-stand.png",
   desc:"いま みえるものを 5つ、さがしてみるのさ。5つ みつけたら つぎは10こだ。いつもちかくにあるものの ぜんぶの なまえが わかるかい？",
   tags:{mood:"anxious", energy:"any", social:"any", body:["heart","breath"], wish:"any"}},
  {t:"きこえるおとを3つさがしてみる",
   g:"からだ",
   img:"act-eyeclose-seiza.png",
   desc:"いま きこえる おとを 3つ さがしてみて。チクタク...チュンチュン.........パオーン。",
   tags:{mood:"anxious", energy:"any", social:"any", body:["heart","breath"], wish:"any"}},
  {t:"すきなにおいをかいでみる",
   g:"からだ",
   img:"act-hug-stuffed-bear.png",
   desc:"ちかくにある すきな においに くんくん してみよう。きもちが なごむよ。",
   tags:{mood:["sad","anxious"], energy:"any", social:["alone","neutral"], body:"any", wish:"any"}},
  {t:"ふわふわしたものをさわってみる",
   g:"からだ",
   img:"act-hug-stuffed-bear.png",
   desc:"ふわふわの タオルや ぬいぐるみを、さわって... ウットリ。",
   tags:{mood:["anxious","sad"], energy:"any", social:["alone","neutral"], body:["heart","breath","fine"], wish:"any"}},
  {t:"ぬいぐるみをだっこしてみる",
   g:"からだ",
   img:"act-hug-stuffed-bear.png",
   desc:"かわいい ぬいぐるみを ギュッと だきしめると、ホッとして あんしんするよ。",
   tags:{mood:["sad","anxious"], energy:"any", social:["alone","neutral"], body:"any", wish:"any"}},
  {t:"きもちをえにかいてみる",
   g:"表現",
   img:"act-paint.png",
   desc:"いまの きもちを えに かいてみよう。ふわふわ？ とげとげ？ ...え、にょろにょろ？",
   tags:{mood:["angry","sad","anxious"], energy:["low","mid"], social:["alone","neutral"], body:"any", wish:"any"}},
  {t:"えんぴつでぐるぐるかいてみる",
   g:"表現",
   img:"act-paint.png",
   desc:"かみに えんぴつで ぐるぐる かくだけで、きもちが スッキリするよ。ついでに、うでの うんどうにもなる。",
   tags:{mood:["angry","anxious"], energy:["high","mid"], social:["alone","neutral"], body:["fine","heart"], wish:"any"}},
  {t:"きもちをノートにかいてみる",
   g:"表現",
   img:"act-writing-letter.png",
   desc:"いま おもっていることを、ノートに かきだして みるってのは、どう？",
   tags:{mood:["sad","angry","anxious"], energy:["low","mid"], social:["alone","neutral"], body:"any", wish:"any"}},
  {t:"しんぱいをノートにかいてみる",
   g:"表現",
   img:"act-writing-letter.png",
   desc:"しんぱいなことを ぜんぶ かくと、あたまの なかが スッキリするよ。",
   tags:{mood:"anxious", energy:["low","mid"], social:["alone","neutral"], body:"any", wish:"any"}},
  {t:"えをかいてみる",
   g:"表現",
   img:"act-paint.png",
   desc:"すきなものでも きもちでも、なんでも じゆうに えに してみよう。もし なにもおもいつかなかったら、わたしの すきなもの、かいてよ。 もぐら。",
   tags:{mood:["sad","anxious"], energy:["low","mid"], social:["alone","neutral"], body:"any", wish:"any"}},
  {t:"みつけたものをえにかいてみる",
   g:"表現",
   img:"act-paint.png",
   desc:"めのまえに あるものを じっくり みて、えに かいてみよう。",
   tags:{mood:["sad","happy"], energy:["mid","low"], social:["alone","neutral"], body:"fine", wish:"nothing"}},
  {t:"だれかにおてがみをかいてみる",
   g:"表現",
   img:"act-writing-letter.png",
   desc:"だれかに おてがみを かいてみよう。きもちが つたわると いいね。",
   tags:{mood:"happy", energy:["high","mid"], social:"social", body:"fine", wish:"talk"}},
  {t:"ちいさなこえでうたってみる",
   g:"表現",
   img:"act-sing.png",
   desc:"ちいさな こえで、すきな うたを くちずさむ。きみだけの だいじな コンサート。",
   tags:{mood:["sad","anxious"], energy:["low","mid"], social:["alone","neutral"], body:["fine","breath","bad"], wish:"nothing"}},
  {t:"おおきなくちであくびしてみる",
   g:"表現",
   img:"act-yawn.png",
   desc:"おもいきり おおきく あくびして、からだを ゆるめて みよう。",
   tags:{mood:["angry","anxious"], energy:"any", social:"any", body:["breath","fine"], wish:"any"}},
  {t:"きもちをことばにしてみる",
   g:"表現",
   img:"act-talk-concern.png",
   desc:"「かなしい」とか 「つかれた」とか。いまの きもちを こえにだそう。",
   tags:{mood:["sad","anxious"], energy:["low","mid"], social:["alone","neutral","social"], body:["fine","bad","heart"], wish:"talk"}},
  {t:"しんぱいをことばにしてみる",
   g:"表現",
   img:"act-talk-concern.png",
   desc:"なにが しんぱいか ことばで いってみるだけで、すこし らくに なるよ。",
   tags:{mood:"anxious", energy:["low","mid"], social:["alone","neutral","social"], body:["fine","heart","breath"], wish:"talk"}},
  {t:"「かなしいな」ってつぶやいてみる",
   g:"表現",
   img:"act-lay-lonely.png",
   desc:"「かなしいな」と ちいさく つぶやくだけで、かなしいきもちが ちょっとだけ おそとにいって くれるのさ。",
   tags:{mood:"sad", energy:"any", social:"any", body:"any", wish:"any"}},
  {t:"「だいじょうぶ」ってつぶやいてみる",
   g:"表現",
   img:"act-cheer-sheself.png",
   desc:"「だいじょうぶ」って じぶんに いいきかせて みよう。だいじょうぶじゃなかったら、また もどってきてね。",
   tags:{mood:"anxious", energy:"any", social:"any", body:["fine","heart","breath"], wish:"any"}},
  {t:"「いまここにいる」ってかんじてみる",
   g:"表現",
   img:"act-closeeyes-char.png",
   desc:"いま、きみは なんていうところにいて だれといて、どんなふくをきて、だれとはなしてる？ かんがえてみて。",
   tags:{mood:"anxious", energy:"any", social:"any", body:["heart","breath"], wish:"any"}},
  {t:"100までかぞえてみる",
   g:"表現",
   img:"act-thinking-stand.png",
   desc:"1から 100まで、ゆっくり こころのなかで かぞえて みよう。",
   tags:{mood:["angry","anxious"], energy:"any", social:"any", body:["fine","heart"], wish:"any"}},
  {t:"てをぎゅっとしてからひらいてみる",
   g:"表現",
   img:"act-hold-hand.png",
   desc:"てを ギュッと にぎって、パッと ひらくのを くりかえして みて。20かいぐらいまでは、おもしろい。30かいぐらい すると、なにしてるんだろうって おもう。100かいやると、てが つかれちゃった......。",
   tags:{mood:["angry","anxious"], energy:"any", social:"any", body:["heart","fine"], wish:"any"}},
  {t:"やりたいことをリストにかいてみる",
   g:"表現",
   img:"act-writing.png",
   desc:"いま きみがやりたいことを リストに すると、たのしい きぶんに なっちゃうね。わたしはいま、おふとんで いっぱい ねたい。",
   tags:{mood:"happy", energy:"any", social:["alone","neutral"], body:"fine", wish:"any"}},
  {t:"きょうのことをにっきにかいてみる",
   g:"表現",
   img:"act-writing.png",
   desc:"きょう あったことを にっきに かいてみよう。",
   tags:{mood:"happy", energy:"any", social:["alone","neutral"], body:"fine", wish:"any"}},
  {t:"きょうよかったことをひとつかんがえてみる",
   g:"表現",
   img:"act-thinking-stand.png",
   desc:"きょう よかったことを、ひとつ おもいだして みるの。",
   tags:{mood:["sad","anxious"], energy:"any", social:["alone","neutral"], body:"any", wish:"any"}},
  {t:"きょうよかったことを100こかんがえてみる!",
   g:"表現",
   img:"act-thinking-stand.png",
   desc:"きょう よかったことを、100こ めざして おもいだす。",
   tags:{mood:"happy", energy:["high","mid"], social:["alone","neutral"], body:"fine", wish:["nothing","play"]}},
  {t:"ありがとうをつたえてみる",
   g:"表現",
   img:"act-talk-with-friend.png",
   desc:"だれかに「ありがとう」を つたえると、きみも あいても ハッピーせいじんに なるよ。",
   tags:{mood:"happy", energy:["high","mid"], social:"social", body:"fine", wish:"talk"}},
  {t:"すきなことにちょうせんしてみる",
   g:"表現",
   img:"act-play-with-friends.png",
   desc:"すきな ことに、おもいきり ちょうせん してみようぜ！",
   tags:{mood:"happy", energy:"high", social:["alone","neutral","social"], body:"fine", wish:"play"}},
  {t:"おきにいりのものをながめてみる",
   g:"表現",
   img:"act-play-with-dolls.png",
   desc:"おきにいりの ものを、じっくり じーっと ながめて みよう。どこがすき？",
   tags:{mood:["sad","anxious"], energy:"any", social:["alone","neutral"], body:"any", wish:"any"}},
  {t:"すきなものをあつめてみる",
   g:"表現",
   img:"act-play-with-dolls.png",
   desc:"ちかくにある じぶんの すきなものを あつめて ならべてみると、たのしい きぶんに なるんだぜ。",
   tags:{mood:"happy", energy:["high","mid"], social:["alone","neutral"], body:"fine", wish:"play"}},
  {t:"たのしいことをかんがえてみる",
   g:"表現",
   img:"act-stay-with-adult-2.png",
   desc:"たのしい ことを、あたまの なかで いっぱい そうぞう してみよう！",
   tags:{mood:"happy", energy:"any", social:"any", body:"fine", wish:"any"}},
  {t:"おもしろいかたちのくもをさがしてみる",
   g:"表現",
   img:"act-looking-at-clouds.png",
   desc:"そらの くもの なかに、おもしろい かたちを みつけて みるのさ。あ、あれはマントヒヒ！",
   tags:{mood:["sad","anxious"], energy:["low","mid"], social:["alone","neutral","social"], body:["fine","breath"], wish:"nothing"}},
  {t:"あたりをスキップしてみる",
   g:"発散",
   img:"act-jump-happy.png",
   desc:"おなじばしょを ぐるぐる スキップするマン さんじょう！",
   tags:{mood:["happy","angry"], energy:"high", social:["alone","neutral","social"], body:"fine", wish:"play"}},
  {t:"おもいっきりいきをだしてみる",
   g:"発散",
   img:"act-deepbreath.png",
   desc:"「ふぅ〜」っておおきく いきをだすと、からだのちからがぬけるよ。",
   tags:{mood:["sad","anxious","angry"], energy:"any", social:"any", body:["breath","heart","fine"], wish:"any"}},
  {t:"ぐるぐるまわってみる",
   g:"発散",
   img:"act-run-plain.png",
   desc:"そのばで ぐるぐる まわってみよう。わかいうちしか できないらしい。",
   tags:{mood:["angry","happy"], energy:"high", social:["alone","neutral"], body:"fine", wish:"play"}},
  {t:"ねっころがってみる",
   g:"発散",
   img:"act-laydown.png",
   desc:"ゆかにごろんとねっころがって、だらーんとしてみる。",
   tags:{mood:["sad","anxious"], energy:["low","verylow"], social:"any", body:["fine","bad"], wish:"any"}},
  {t:"ストローでぶくぶくしてみる",
   g:"発散",
   img:"act-drink.png",
   desc:"コップに ストローをいれて ぶくぶくするのって、おもしろい。",
   tags:{mood:["angry","happy","anxious"], energy:"any", social:["alone","neutral"], body:["fine","breath"], wish:"any"}},
  {t:"かみをはさみでぐるぐるきってみる",
   g:"発散",
   img:"",
   desc:"かみを ぐるぐるにきる。ながーく きればきるほど びよーん。",
   tags:{mood:["angry","anxious"], energy:"any", social:["alone","neutral"], body:"fine", wish:"any"}},
  {t:"もこもこのもうふにくるまってみる",
   g:"落ち着き",
   img:"act-laydown-rest.png",
   desc:"もこもこの ものに くるまると、ひとりだけの ばしょの できあがり。ふまれないように きをつけてね。",
   tags:{mood:["sad","anxious"], energy:["low","verylow"], social:["alone","neutral"], body:["fine","bad"], wish:"sleep"}},
  {t:"くらいへやでぼーっとしてみる",
   g:"落ち着き",
   img:"act-sitting-fav-place-sad.png",
   desc:"でんきをけして、しずかなくらい へやで しばらく ぼーっとしてみよう。",
   tags:{mood:["sad","anxious"], energy:["low","verylow"], social:["alone","neutral"], body:"any", wish:"any"}},
  {t:"とけいのおとをきいてみる",
   g:"落ち着き",
   img:"act-eyeclose-seiza.png",
   desc:"チクタク チクタク。とけいの おとだけに しゅうちゅう してみよう。",
   tags:{mood:"anxious", energy:["low","mid"], social:["alone","neutral"], body:["heart","breath"], wish:"nothing"}},
  {t:"ひざをむねにかかえてみる",
   g:"落ち着き",
   img:"act-sitting-fav-place-sad.png",
   desc:"ひざをかかえてまるくなると、こころがすこしおちつくよ。おきあがりこぼしのように ゆれてみよう。",
   tags:{mood:["sad","anxious"], energy:["low","verylow"], social:["alone","neutral"], body:["fine","bad"], wish:"nothing"}},
  {t:"いすにふかくすわってみる",
   g:"落ち着き",
   img:"act-sitting-fav-chair.png",
   desc:"いすに あさく すわるのと、ふかく すわるのって なんだかぜんぜん ちがうかんじがする。",
   tags:{mood:["anxious","sad"], energy:["low","mid"], social:["alone","neutral"], body:["fine","heart","breath"], wish:"nothing"}},
  {t:"めをとじて すきなばしょをそうぞうしてみる",
   g:"落ち着き",
   img:"act-eyeclose-seiza.png",
   desc:"めをとじて、いちばん すきなばしょに いるところを そうぞうしてみよう。",
   tags:{mood:["anxious","sad"], energy:"any", social:"any", body:["fine","heart","breath"], wish:"any"}},
  {t:"なにもしないじかんを3ふんつくってみる",
   g:"落ち着き",
   img:"act-sitting-smile.png",
   desc:"なにもしない！ただそれだけ。3ふんだけ ぼーーーっ。",
   tags:{mood:["sad","anxious"], energy:["low","verylow"], social:"any", body:"any", wish:"any"}},
  {t:"めをとじて すきなおとをそうぞうしてみる",
   g:"落ち着き",
   img:"act-eyeclose-seiza.png",
   desc:"なみのおと、あめのおと、もりのおと…すきなおとをそうぞうしてみよう。",
   tags:{mood:["anxious","sad"], energy:"any", social:"any", body:["fine","heart","breath"], wish:"any"}},
  {t:"あしたやりたいことをかんがえてみる",
   g:"気分転換",
   img:"act-thinking-stand.png",
   desc:"あしたの たのしみなことを 1つかんがえると、きもちがすこし かるくなるよ。",
   tags:{mood:["sad","anxious"], energy:"any", social:"any", body:"any", wish:"any"}},
  {t:"すきなたべものをかんがえてみる",
   g:"気分転換",
   img:"act-thinking-chair.png",
   desc:"いちばん すきなたべものを おもいうかべる。ちなみに わたしは いま かきのたねを おもいうかべています。ジュルリ...。",
   tags:{mood:["sad","anxious"], energy:"any", social:"any", body:["bad","fine"], wish:"any"}},
  {t:"まどのそとをながめてみる",
   g:"気分転換",
   img:"act-looking-at-clouds.png",
   desc:"まどのそとを ぼーっとながめるだけで、きもちが ひろくなるよ。",
   tags:{mood:["sad","anxious"], energy:"any", social:"any", body:"any", wish:"any"}},
  {t:"てのひらをながめてみる",
   g:"気分転換",
   img:"act-thinking-stand.png",
   desc:"じぶんの てのひらを ぢっと みてみる。",
   tags:{mood:["anxious","sad"], energy:"any", social:"any", body:"any", wish:"any"}},
  {t:"かみをおりたたんで びょうぶにしてみる",
   g:"気分転換",
   img:"act-origami.png",
   desc:"かみを じゃばらに おりたたんで、びょうぶを つくってみよう。おなじ はばで おるのが コツ。",
   tags:{mood:["sad","anxious"], energy:["low","mid"], social:["alone","neutral"], body:["fine","bad"], wish:"nothing"}},
  {t:"ゆかにねころんでてんじょうをみてみる",
   g:"気分転換",
   img:"act-laydown-thinking.png",
   desc:"てんじょうをじっとみる。ふだん いがいと てんじょうって みないよね。",
   tags:{mood:["sad","anxious"], energy:["low","verylow"], social:"any", body:"any", wish:"any"}},
  {t:"きせつのものをさがしてみる",
   g:"気分転換",
   img:"act-run-outside.png",
   desc:"そとにでて、いまの きせつにしか ないものを さがしてみよう。",
   tags:{mood:["sad","anxious"], energy:["mid","low"], social:["alone","neutral","social"], body:"fine", wish:"nothing"}},
  {t:"すきなキャラクターのものまねしてみる",
   g:"気分転換",
   img:"act-laugh-hardly.png",
   desc:"すきなキャラクターの せりふや しぐさを やってみよう。ﾋﾟｶﾁｭﾋﾟｯｶ！",
   tags:{mood:["angry","happy"], energy:["mid","high"], social:["alone","neutral"], body:"fine", wish:"play"}},
  {t:"いまのきもちのかおをしてみる",
   g:"気分転換",
   img:"act-stand-mad.png",
   desc:"おこっているなら おこっているかお。いやなきもちなら え～ってかお。おちこんでるなら おちこんでる おかお。",
   tags:{mood:["angry","sad"], energy:["mid","high"], social:["alone","neutral"], body:"fine", wish:"play"}},
  {t:"ぺんをくるくるまわしてみる",
   g:"気分転換",
   img:"act-writing.png",
   desc:"ペンまわしに ちょうせんだ！ むずかしいぞ できるかな？",
   tags:{mood:["anxious","angry"], energy:["mid","high"], social:["alone","neutral","social"], body:"fine", wish:"play"}},
  {t:"ほしいものリストをかいてみる",
   g:"気分転換",
   img:"act-writing.png",
   desc:"いつか ほしいものを ぜ～んぶ かいてみよう。かくだけで わくわくしてくるよ。わたしがいま ほしいのは スリーディー プリンター。",
   tags:{mood:["sad","happy"], energy:"any", social:["alone","neutral"], body:"fine", wish:"any"}},
  {t:"ぼうしをさかさまにかぶってみる",
   g:"気分転換",
   img:"",
   desc:"ぼうしを さかさまに かぶるだけで、なんか ちがうじぶんに なれるよ。",
   tags:{mood:["angry","happy"], energy:["mid","high"], social:["alone","neutral"], body:"fine", wish:"play"}},
  {t:"いまいるばしょをたんけんするつもりで あるいてみる",
   g:"気分転換",
   img:"act-run-outside.png",
   desc:"みなれたへやでも「はじめてきた たんけんか」のつもりで たんけんしてみると しんはっけん！",
   tags:{mood:["sad","anxious"], energy:["mid","low"], social:["alone","neutral","social"], body:"fine", wish:"nothing"}},
  {t:"だれかにすきなものをきいてみる",
   g:"人とつながる",
   img:"act-talk-with-friend.png",
   desc:"「さいきん はまってるものは なに？」ってともだちや せんせいに きいてみよう。",
   tags:{mood:["happy","sad"], energy:["mid","high"], social:"social", body:"fine", wish:"talk"}},
  {t:"ひみつをだれかひとりにだけおしえてみる",
   g:"人とつながる",
   img:"act-talk-concern.png",
   desc:"「じつはね...」ってだれかに ちょっとした ひみつを はなしてみよう。",
   tags:{mood:["sad","anxious"], energy:["low","mid"], social:"social", body:["fine","bad"], wish:"talk"}},
  {t:"だれかのいいところをみつけて つたえてみる",
   g:"人とつながる",
   img:"act-talk-with-friend.png",
   desc:"ともだちの すてきなところを 1つみつけて つたえると、ふたりとも うれしくなるよ。あっ、きみは てが あったかくて すてきだね。",
   tags:{mood:"happy", energy:["mid","high"], social:"social", body:"fine", wish:"talk"}},
  {t:"いっしょにしゃしんをとってみる",
   g:"人とつながる",
   img:"",
   desc:"ともだちや せんせいと いっしょに しゃしんをとる。ハイ ポーズ！",
   tags:{mood:"happy", energy:["mid","high"], social:"social", body:"fine", wish:"play"}},
  {t:"てをほっぺにあててみる",
   g:"からだ",
   img:"",
   desc:"りょうてを ほっぺにそっと あててみよう。そのまま むにーって のばしたら .........へんがお。",
   tags:{mood:["sad","anxious"], energy:["low","mid"], social:["alone","neutral"], body:["fine","bad","heart"], wish:"nothing"}},
  {t:"あしのゆびをぎゅっとにぎってひらいてみる",
   g:"からだ",
   img:"act-sitting-smile.png",
   desc:"ちょっとのあいだ くつしたをぬいで、あしのゆびを うごかしてみる。くつしたって、いがいと あしを しめつけているから ぬいで すっきり。",
   tags:{mood:"anxious", energy:"any", social:"any", body:["heart","breath"], wish:"any"}},
  {t:"はだしになってみる",
   g:"からだ",
   img:"act-stand-normal.png",
   desc:"くつとくつしたをぬいで、はだしになってみよう。ゆかのひんやりがきもちいいよ。",
   tags:{mood:["anxious","sad"], energy:"any", social:"any", body:["heart","breath","fine"], wish:"any"}},
  {t:"だれかにせなかをさすってもらう",
   g:"人とつながる",
   img:"act-stay-with-adult-2.png",
   desc:"だれかに そばにいてもらって、せなかを やさしく さすってもらおう。しずかにでも、なにか はなしながらでも いい。",
   tags:{mood:["sad","anxious"], energy:["verylow","low","mid"], social:"social", body:["heart","breath","bad"], wish:"nothing"}},
  {t:"いらいらしているわけをかみにかいてみる",
   g:"表現",
   img:"act-writing.png",
   desc:"なにがいやだったか、かみにぜんぶかいてみよう。",
   tags:{mood:"angry", energy:["mid","low"], social:["alone","neutral"], body:"any", wish:"any"}},
  {t:"きょうのできごとをえにしてみる",
   g:"表現",
   img:"act-paint.png",
   desc:"きょうあったことを、いちまいの えに かいてみよう。",
   tags:{mood:["happy","sad"], energy:"any", social:["alone","neutral"], body:"fine", wish:"any"}},
  {t:"いまのきもちはなにいろかかんがえてみる",
   g:"表現",
   img:"act-thinking-stand.png",
   desc:"いまのきもちはなにいろ？ あおいろかな。まっかっかかな。...にじいろ かしら。",
   tags:{mood:["sad","anxious","angry"], energy:"any", social:"any", body:"any", wish:"any"}},
  {t:"じぶんへのほめことばをかいてみる",
   g:"表現",
   img:"act-writing-letter.png",
   desc:"じぶんを ほめることばを かみに かいてみよう。「きょうは いっぱいねて えらかった！」とか。",
   tags:{mood:["sad","anxious"], energy:"any", social:["alone","neutral"], body:"any", wish:"any"}},
  {t:"なりたいじぶんをかんがえてみる",
   g:"表現",
   img:"act-thinking-stand.png",
   desc:"どんなじぶんになりたいか、かみにかいてみよう。わたしはね、ほかのひとを いっぱい ほめられる ひとになりたいな。",
   tags:{mood:["happy","sad"], energy:"any", social:"any", body:"fine", wish:"any"}},
  {t:"「もしも」のはなしをかんがえてみる",
   g:"表現",
   img:"act-thinking-chair.png",
   desc:"「もしも おうちの となりに ゆうえんちがあったら」とか、じゆうに そうぞうしてみよう！",
   tags:{mood:["happy","sad"], energy:"any", social:"any", body:"fine", wish:"any"}},
  {t:"ひとにはなすのがむずかしいことをかいてみる",
   g:"表現",
   img:"act-writing-letter.png",
   desc:"だれにもいえないことを かみにかいて、そのまま だれにもみせずに びりびりにして、すてちゃう。",
   tags:{mood:["sad","angry"], energy:["low","mid"], social:["alone","neutral"], body:"any", wish:"any"}},
  {t:"やってみたいことをたくさんかいてみる",
   g:"表現",
   img:"act-writing.png",
   desc:"いつか やってみたいことを たくさん かきだしてみよう。",
   tags:{mood:"happy", energy:"any", social:["alone","neutral"], body:"fine", wish:"any"}},
  {t:"じぶんのどうぶつをかんがえてみる",
   g:"表現",
   img:"act-thinking-chair.png",
   desc:"じぶんって、どうぶつで いったら、あれかなあって かんがえてみる。",
   tags:{mood:"happy", energy:"any", social:"any", body:"fine", wish:"any"}},
  {t:"じぶんのいいところを 5つかぞえてみる",
   g:"表現",
   img:"act-thinking-stand.png",
   desc:"じぶんの いいところを 5つ かんがえて かいてみよう。えっと、ひとつめは...「ねるのが とくい」っと...",
   tags:{mood:["sad","anxious"], energy:"any", social:["alone","neutral"], body:"any", wish:"any"}},
  {t:"いまのきもちはおとでいうとなにかかんがえてみる",
   g:"表現",
   img:"act-thinking-stand.png",
   desc:"いまのきもちは「ドーン」か「しーん」か「ぐるぐる」か、おとで かんがえて みよう。",
   tags:{mood:["angry","sad","anxious"], energy:"any", social:"any", body:"any", wish:"any"}},
  {t:"てのこうにえをかいてみる",
   g:"表現",
   img:"act-paint.png",
   desc:"てのひらに ペンで ちいさなえを かいてみよう。",
   tags:{mood:["happy","sad"], energy:"any", social:["alone","neutral"], body:"fine", wish:"any"}},
  {t:"じぶんだけのランキングをつくってみる",
   g:"表現",
   img:"act-writing.png",
   desc:"デケデケデケ...デデン！いちいは なんと、でんちゅう になりました！",
   tags:{mood:"happy", energy:"any", social:["alone","neutral"], body:"fine", wish:"any"}},
];


/* ── きもちごとの見出し・説明・アイコン設定 ──
   mood の回答値（happy/sad/angry/anxious/neutral）ごとに設定する
   ============================================== */
const MD = {

  angry: {
    topImg:  "mad",
    ce_ikey: "mad",
    ct:      "もやもや",
    ttls: [
      "もやもやしてるんだね",
      "なんかイライラしているんだね",
      "むかーってなっているんだね",
    ],
    descs: [
      "なにかがうまくいかなくて、むかーっとしちゃうこと、だれにでもあるよ。そのエネルギーをそとにだしてあげよう。",
      "イライラしてるきもち、ちゃんとわかるよ。そういうときはからだをうごかすとすっきりするよ！",
      "もやもやしてるとき、むりにわらわなくていいよ。すこしずつきもちをだしてみよう。",
    ],
  },

  sad: {
    topImg:  "cry",
    ce_ikey: "cry",
    ct:      "かなしい",
    ttls: [
      "かなしいきもちなんだね",
      "なんかかなしくなっちゃったんだね",
      "しんどいきもちなんだね",
    ],
    descs: [
      "なみだがでそうなくらいかなしいこと、あるよね。そのきもちはそのままでいいよ。ゆっくりしてね。",
      "かなしいとき、むりにがんばらなくていいよ。じぶんのきもちをたいせつにしてね。",
      "しんどいきもち、ひとりでかかえなくていいよ。だれかそばにいるよ。",
    ],
  },

  anxious: {
    topImg:  "puzzled",
    ce_ikey: "puzzled",
    ct:      "しんぱい",
    ttls: [
      "なんだかドキドキしてるんだね",
      "しんぱいなきもちなんだね",
      "こころがざわざわしてるんだね",
    ],
    descs: [
      "しんぱいなことやこわいことがあると、からだもどきどきしちゃうよね。ひとつずつ、ゆっくりいこうね。",
      "ざわざわするきもち、ちゃんとわかるよ。いっしょにおちつこうね。",
      "どきどきしてるとき、ひとりでかかえなくていいよ。そばにいるよ。",
    ],
  },

  happy: {
    topImg:  "smile",
    ce_ikey: "smile",
    ct:      "たのしい",
    ttls: [
      "たのしいきもちなんだね！",
      "うれしいきもちなんだね！",
      "わくわくしてるんだね！",
    ],
    descs: [
      "わあ、うれしいな！そのきもち、だいじにしてね。たのしいエネルギーをいっぱいつかってみよう！",
      "たのしいきもちはまわりのひともうれしくさせるよ。とってもすてき！",
      "わくわくしてるって、すてきだね！そのきもちをいっぱいたのしんでね！",
    ],
  },

  neutral: {
    topImg:  "normal",
    ce_ikey: "normal",
    ct:      "ふつう",
    ttls: [
      "なんとなくそんなきもちなんだね",
      "ぼんやりしてるかんじなんだね",
      "まあまあなきもちなんだね",
    ],
    descs: [
      "おおきなきもちはないけど、なんとなくぼんやりしてたり、つかれてたりするのかもね。ゆっくりしてね。",
      "ふつうのときも、じぶんのきもちをきいてあげるのはたいせつなことだよ。",
      "まあまあなきもちのとき、なにかひとつちいさなことをやってみると、きもちがかわるかも。",
    ],
  },

};