/* ==============================================
   data.js
   きもちチェックのデータファイル
   ・BUBBLES : 特効薬バブルの一覧
   ・MD      : きもちごとの見出し・説明・アイコン設定
   ============================================== */


/* ── バブルのジャンル別カラー定義 ── */
const BC = {
  発散:       {c:"#FBEAF0", tc:"#72243E"},  /* ピンク系 */
  落ち着き:   {c:"#E1F5EE", tc:"#085041"},  /* 緑系 */
  気分転換:   {c:"#FAEEDA", tc:"#633806"},  /* 黄色系 */
  人とつながる:{c:"#E6F1FB", tc:"#0C447C"},  /* 青系 */
  からだ:     {c:"#EAF3DE", tc:"#27500A"},  /* 薄緑系 */
  表現:       {c:"#EEEDFE", tc:"#3C3489"},  /* 紫系 */
};


/* ── 全特効薬バブルのデータ ──
   フィールドの説明：
     t    : 表示テキスト
     g    : ジャンル（色の種類）
     img  : 画像ファイル名（acts/フォルダ内）
     desc : 詳細画面に表示する解説文（50文字程度）
     tags : スコアリング用タグ
   ============================================== */
const BUBBLES = [
  {t:"そとでジャンプしてみる",
   g:"発散",
   img:"act-jump-happy.png",
   desc:"たかく ジャンプして、もやもや エネルギーを そとに だしちゃおう！",
   tags:{mood:["angry","happy"], energy:"high", social:["alone","neutral"], body:["fine","heart"], wish:"play"}},
  {t:"そのばではしってみる",
   g:"発散",
   img:"act-jump-happy.png",
   desc:"そのばで こばしりするだけでも、からだが すっきりしちゃうかもね。",
   tags:{mood:["angry","happy"], energy:"high", social:["alone","neutral"], body:["fine","heart"], wish:"play"}},
  {t:"かみをビリビリやぶいてみる",
   g:"発散",
   img:"act-tear-paper.png",
   desc:"やぶってもいい かみを ビリビリ やぶくと、きもちが すっきりするのさ！",
   tags:{mood:"angry", energy:["high","mid"], social:"alone", body:["fine","heart"], wish:["nothing","any"]}},
  {t:"まくらにさけんでみる",
   g:"発散",
   img:"act-scream-in-pillow.png",
   desc:"まくらに かおを うずめて、「わーっ！」と おおごえで さけんでみよう。",
   tags:{mood:"angry", energy:["high","mid"], social:"alone", body:["fine","breath"], wish:["nothing","any"]}},
  {t:"ぎゅーっててをにぎってみる",
   g:"発散",
   img:"act-jidanda.png",
   desc:"こぶしを ギュッと にぎって、 パワーを ためよう。",
   tags:{mood:"angry", energy:["high","mid"], social:["alone","neutral"], body:"heart", wish:["nothing","play"]}},
  {t:"おもいきりのびをしてみる",
   g:"発散",
   img:"act-stretch.png",
   desc:"うえに おおきく のびをして、ゆ～っくり いきを はきだす。",
   tags:{mood:["angry","anxious"], energy:["high","mid"], social:["alone","neutral"], body:"breath", wish:["nothing","play"]}},
  {t:"おもいっきりわらってみる",
   g:"発散",
   img:"act-dance.png",
   desc:"たのしいことを おもいだして、こえにだして わらってみるのだ！ ガハハハハ！",
   tags:{mood:"happy", energy:"high", social:["alone","social"], body:"fine", wish:"play"}},
  {t:"トイレでゆっくりいきをはいてみる",
   g:"落ち着き",
   img:"act-deepbreath-in-bathroom.png",
   desc:"おちつける トイレへ いって、いきを「はー」って だしてみる。",
   tags:{mood:"angry", energy:["high","mid"], social:"alone", body:"breath", wish:["nothing","play"]}},
  {t:"ゆっくりしんこきゅうしてみる",
   g:"落ち着き",
   img:"act-deepbreath.png",
   desc:"むねに てをあてて、ふくらませながら ふかーく すってみるのだ。",
   tags:{mood:["anxious","angry"], energy:["low","mid"], social:["alone","neutral"], body:"breath", wish:["nothing","sleep"]}},
  {t:"しんこきゅうを3かいしてみる",
   g:"落ち着き",
   img:"act-deepbreath.png",
   desc:"ゆっくり 3かい しんこきゅう するだけで、きもちが おちつくよ。",
   tags:{mood:["anxious","angry"], energy:["low","mid"], social:["alone","neutral"], body:"heart", wish:["nothing","sleep"]}},
  {t:"4びょうすって8びょうはいてみる",
   g:"落ち着き",
   img:"act-deepbreath.png",
   desc:"4びょうかけて すって、8びょうかけて ゆっくり はいてみよう。",
   tags:{mood:"anxious", energy:["low","mid"], social:["alone","neutral"], body:"heart", wish:["nothing","sleep"]}},
  {t:"めをとじて10かぞえてみる",
   g:"落ち着き",
   img:"act-closeeyes-char.png",
   desc:"めを とじて、ゆっくり 10まで かぞえながら おちつこう。",
   tags:{mood:"anxious", energy:["low","mid"], social:"alone", body:["heart","breath"], wish:"nothing"}},
  {t:"すわってめをとじてみる",
   g:"落ち着き",
   img:"act-closeeyes-char.png",
   desc:"らくな しせいで すわって、めを とじて しばらく やすむのも いいよね。",
   tags:{mood:["sad","anxious"], energy:"low", social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"しばらくひとりでいてみる",
   g:"落ち着き",
   img:"act-laydown.png",
   desc:"しずかな ばしょで、ひとりぼっちの じかんを つくってみよう。",
   tags:{mood:["angry","sad"], energy:["low","mid"], social:"alone", body:["fine","breath"], wish:"nothing"}},
  {t:"すきなばしょですわってみる",
   g:"落ち着き",
   img:"act-sitting-fav-place.png",
   desc:"きみが いちばん おちつける ばしょは どこかな？ そこにいって じっとしてみよう。",
   tags:{mood:["anxious","sad"], energy:"low", social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"めをとじてやすんでみる",
   g:"落ち着き",
   img:"act-closeeyes-char.png",
   desc:"めを とじて、からだの ちからを ぬいて ゆっくり やすもうぜ。",
   tags:{mood:["sad","anxious"], energy:"verylow", social:"alone", body:["fine","bad"], wish:"sleep"}},
  {t:"きょうはゆっくりやすんでみる",
   g:"落ち着き",
   img:"act-laydown.png",
   desc:"きょうは むりせず、のんびり すごして みるってのはどう？",
   tags:{mood:["sad","anxious"], energy:"verylow", social:["alone","neutral"], body:["fine","bad"], wish:"sleep"}},
  {t:"ゆっくりあるいてみる",
   g:"落ち着き",
   img:"act-walk-with-adult.png",
   desc:"いそがず ゆっくり あるいて、あしのうらを かんじてみるのさ。なめくじさんより おそくなれるかい？",
   tags:{mood:["sad","anxious"], energy:"low", social:["alone","neutral"], body:["fine","bad"], wish:["nothing","sleep"]}},
  {t:"そとをおさんぽしてみる",
   g:"落ち着き",
   img:"act-run-outside.png",
   desc:"そとの くうきを すいながら、のんびり おさんぽして みない？",
   tags:{mood:["happy","sad"], energy:["high","mid"], social:["alone","neutral"], body:"fine", wish:"play"}},
  {t:"5ふんだけそとをあるいてみる",
   g:"落ち着き",
   img:"act-run-outside.png",
   desc:"5ふんだけ そとに でて、うえを むいて あるいてみよう。...でも、ころばないでね。",
   tags:{mood:["sad","angry"], energy:"mid", social:["alone","neutral"], body:"fine", wish:"nothing"}},
  {t:"そとではしってみる",
   g:"落ち着き",
   img:"act-run-outside.png",
   desc:"そとで すこし はしってみると、きもちが スッキリするかも！！",
   tags:{mood:["happy","angry"], energy:"high", social:["alone","neutral"], body:"fine", wish:"play"}},
  {t:"すきなうたをきいてみる",
   g:"気分転換",
   img:"act-listen-music.png",
   desc:"すきな きょくを ぜんりょくで きいてみよう。",
   tags:{mood:["sad","anxious","angry"], energy:["low","mid"], social:"alone", body:["fine","bad"], wish:["nothing","sleep"]}},
  {t:"すきなどうがをみてみる",
   g:"気分転換",
   img:"404.png",
   desc:"すきな どうがや アニメを みて、きぶんを かえちゃうのさ。",
   tags:{mood:"sad", energy:"low", social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"すきなうたにあわせておどってみる",
   g:"気分転換",
   img:"act-dance.png",
   desc:"すきな きょくに あわせて、からだを うごかして たのしもう！ ずんちゃっちゃ ずんちゃっちゃ。",
   tags:{mood:"happy", energy:"high", social:["alone","social"], body:"fine", wish:"play"}},
  {t:"すきなほんをよんでみる",
   g:"気分転換",
   img:"act-read-book.png",
   desc:"すきな ほんを ひらいて、ものがたりの せかいへ レッツらゴー！",
   tags:{mood:["sad","anxious"], energy:"low", social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"すきなキャラクターをながめてみる",
   g:"気分転換",
   img:"404.png",
   desc:"すきな キャラクターの グッズや えを、じっくり ながめてみよう。",
   tags:{mood:"sad", energy:"low", social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"すきなキャラクターのえをかいてみる",
   g:"気分転換",
   img:"404.png",
   desc:"すきな キャラクターの えを、じゆうに かいてみるのさ。",
   tags:{mood:"happy", energy:["high","mid"], social:"alone", body:"fine", wish:"play"}},
  {t:"あたらしいあそびをためしてみる",
   g:"気分転換",
   img:"404.png",
   desc:"やったことがない あそびを、ひとつ ためしてみよう。ワクワク！",
   tags:{mood:"happy", energy:"high", social:["alone","neutral"], body:"fine", wish:"play"}},
  {t:"すきなあそびをしてみてみる",
   g:"気分転換",
   img:"404.png",
   desc:"いちばん すきな あそびで、おもいきり たのしんじゃう！！？！",
   tags:{mood:"happy", energy:["high","mid"], social:["alone","neutral","social"], body:"fine", wish:"play"}},
  {t:"おりがみをおってみる",
   g:"気分転換",
   img:"404.png",
   desc:"おりがみを おることに しゅうちゅうすると、きもちが おちつくよ。",
   tags:{mood:["sad","anxious"], energy:"low", social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"ちいさなかたづけをしてみる",
   g:"気分転換",
   img:"404.png",
   desc:"みの まわりを ちょびっと かたづけると、あたまも きもちも ちょびっと スッキリ！",
   tags:{mood:["sad","angry"], energy:"mid", social:"alone", body:"fine", wish:"nothing"}},
  {t:"たいようをあびてみる",
   g:"気分転換",
   img:"404.png",
   desc:"そとに でて、たいようの ひかりを からだじゅうで あびてみよう。くもってたら ごめんね。",
   tags:{mood:"sad", energy:["low","mid"], social:["alone","neutral"], body:["fine","bad"], wish:["nothing","sleep"]}},
  {t:"そとのそらをみあげてみる",
   g:"気分転換",
   img:"404.png",
   desc:"そらを みあげて、くもを ながめてみるのも いいね。くもがひとつもなかったら...... それもステキ。",
   tags:{mood:"anxious", energy:["low","mid"], social:["alone","neutral"], body:"breath", wish:["nothing","sleep"]}},
  {t:"しんらいできるひとにはなしてみる",
   g:"人とつながる",
   img:"act-walk-with-adult.png",
   desc:"しんらいできる ひとに、「ちょっと いい？ かわいいかわいい ぼくちゃんが はなしたいこと あるんだけど」と、いってみる。",
   tags:{mood:["sad","anxious","angry"], energy:["low","mid","verylow"], social:"social", body:["fine","heart","bad"], wish:"talk"}},
  {t:"せんせいにはなしかけてみる",
   g:"人とつながる",
   img:"act-walk-with-adult.png",
   desc:"せんせいに、「はなしを きいてほしいな」と こえを かけてみて。",
   tags:{mood:["sad","anxious"], energy:["low","mid","verylow"], social:"social", body:["fine","bad"], wish:"talk"}},
  {t:"だれかにそばにいてもらう",
   g:"人とつながる",
   img:"act-walk-with-adult.png",
   desc:"だれかに ちかくに いてもらうだけで あんしんしちゃうかも。",
   tags:{mood:"sad", energy:"verylow", social:"social", body:["fine","bad"], wish:["nothing","sleep"]}},
  {t:"やさしいひとのそばにいてみる",
   g:"人とつながる",
   img:"act-walk-with-adult.png",
   desc:"やさしい ひとの ちかくに いるだけで、きもちが らくに なるよ。",
   tags:{mood:"sad", energy:["low","verylow"], social:"social", body:["fine","bad"], wish:["nothing","sleep"]}},
  {t:"おともだちにはなしかけてみる",
   g:"人とつながる",
   img:"act-stand-normal.png",
   desc:"ともだちに、「さいきん どう？」と はなしかけてみるのさ。",
   tags:{mood:["sad","anxious","angry"], energy:["low","mid"], social:"social", body:["fine","heart"], wish:"talk"}},
  {t:"ともだちをさそってみる",
   g:"人とつながる",
   img:"act-stand-normal.png",
   desc:"ともだちを、「いっしょに なんか しよう！」と さそってみよう。",
   tags:{mood:"happy", energy:"high", social:"social", body:"fine", wish:"play"}},
  {t:"おともだちとわらいあってみる",
   g:"人とつながる",
   img:"act-stand-normal.png",
   desc:"ともだちと いっしょに、わらえる ことをして たのしもう。",
   tags:{mood:"happy", energy:"high", social:"social", body:"fine", wish:"play"}},
  {t:"だれかにえがおをむけてみる",
   g:"人とつながる",
   img:"act-stand-normal.png",
   desc:"あった ひとに えがおを むけてみて。じぶんも きもちが よくなるよ。",
   tags:{mood:"happy", energy:["high","mid"], social:"social", body:"fine", wish:["play","talk"]}},
  {t:"ともだちにありがとうといってみる",
   g:"人とつながる",
   img:"act-stand-normal.png",
   desc:"ともだちに 「ありがとう」を つたえると、ふたりとも ハッピー！",
   tags:{mood:"happy", energy:["high","mid"], social:"social", body:"fine", wish:"talk"}},
  {t:"たのしいきもちをだれかにつたえてみる",
   g:"人とつながる",
   img:"act-stand-normal.png",
   desc:"「たのしかった！」を だれかに はなすと、もっともっと うれしく なるよ。",
   tags:{mood:"happy", energy:["high","mid"], social:"social", body:"fine", wish:"talk"}},
  {t:"だれかをわらわせてみる",
   g:"人とつながる",
   img:"act-stand-normal.png",
   desc:"おもしろいことを はなして、だれかを わらわせて みないかい？",
   tags:{mood:"happy", energy:["high","mid"], social:"social", body:"fine", wish:"talk"}},
  {t:"おともだちのそばにいてみる",
   g:"人とつながる",
   img:"act-stand-normal.png",
   desc:"おともだちの ちかくに いるだけで、しんぱいが やわらぐかもね。",
   tags:{mood:"anxious", energy:["low","mid"], social:"social", body:["fine","heart"], wish:["nothing","talk"]}},
  {t:"みずをゴクっとのんでみる",
   g:"からだ",
   img:"404.png",
   desc:"のみものを ひとくち ゴクッと のんでみて、おちつこうぜ。",
   tags:{mood:"angry", energy:["high","mid"], social:["alone","neutral"], body:["fine","heart"], wish:["nothing","play"]}},
  {t:"つめたいみずをのんでみる",
   g:"からだ",
   img:"404.png",
   desc:"つめたい みずを ゆっくり のんで、からだも こころも クールダウン。",
   tags:{mood:"angry", energy:["high","mid"], social:["alone","neutral"], body:["fine","heart"], wish:["nothing","play"]}},
  {t:"みずをゆっくりのんでみる",
   g:"からだ",
   img:"404.png",
   desc:"みずを ゆっくり すこしずつ のんで、いきを ととのえて みよう。",
   tags:{mood:"anxious", energy:["low","mid"], social:["alone","neutral"], body:"heart", wish:["nothing","sleep"]}},
  {t:"てをあらってすっきりしてみる",
   g:"からだ",
   img:"404.png",
   desc:"てを ていねいに あらって、きもちを すっきり させてみよう。",
   tags:{mood:["sad","angry"], energy:["low","mid"], social:["alone","neutral"], body:"bad", wish:"nothing"}},
  {t:"あしのうらをかんじてみる",
   g:"からだ",
   img:"404.png",
   desc:"あしのうらが ゆかに ついているのを、しっかり かんじて みて。",
   tags:{mood:"anxious", energy:["low","mid"], social:["alone","neutral"], body:"heart", wish:["nothing","sleep"]}},
  {t:"てのひらをひざにおいてみる",
   g:"からだ",
   img:"404.png",
   desc:"てのひらを ひざに おいて、こきゅうだけに しゅうちゅう しよう。",
   tags:{mood:"anxious", energy:["low","mid"], social:["alone","neutral"], body:"heart", wish:["nothing","sleep"]}},
  {t:"みえるものを5つさがしてみる",
   g:"からだ",
   img:"404.png",
   desc:"いま みえるものを 5つ、さがしてみるのさ。5つ みつけたら つぎは10こだ。いつもちかくにあるものの ぜんぶの なまえが わかるかい？",
   tags:{mood:"anxious", energy:["low","mid"], social:["alone","neutral"], body:["heart","breath"], wish:["nothing","sleep"]}},
  {t:"きこえるおとを5つさがしてみる",
   g:"からだ",
   img:"404.png",
   desc:"いま きこえる おとを 5つ さがしてみて。チクタク...チュンチュンチュン.........パオーン。",
   tags:{mood:"anxious", energy:["low","mid"], social:["alone","neutral"], body:["heart","breath"], wish:["nothing","sleep"]}},
  {t:"すきなにおいをかいでみる",
   g:"からだ",
   img:"404.png",
   desc:"ちかくにある すきな においに くんくん してみよう。きもちが なごむよ。",
   tags:{mood:["sad","anxious"], energy:"low", social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"ふわふわしたものをさわってみる",
   g:"からだ",
   img:"404.png",
   desc:"ふわふわの タオルや ぬいぐるみを、さわって... ウットリ。",
   tags:{mood:"anxious", energy:["low","mid"], social:"alone", body:"heart", wish:["nothing","sleep"]}},
  {t:"ぬいぐるみをだっこしてみる",
   g:"からだ",
   img:"404.png",
   desc:"かわいい ぬいぐるみを ギュッと だきしめると、ホッとして あんしんするよ。",
   tags:{mood:["sad","anxious"], energy:"low", social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"きもちをえにかいてみる",
   g:"表現",
   img:"404.png",
   desc:"いまの きもちを えに かいてみよう。にこにこ？ とげとげ？ ...え、にょろにょろ？",
   tags:{mood:["angry","sad"], energy:["low","mid"], social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"えんぴつでぐるぐるかいてみる",
   g:"表現",
   img:"404.png",
   desc:"かみに えんぴつで ぐるぐる かくだけで、きもちが スッキリするよ。ついでに、うでの うんどうにもなる。",
   tags:{mood:"angry", energy:["high","mid"], social:"alone", body:["fine","heart"], wish:"nothing"}},
  {t:"きもちをノートにかいてみる",
   g:"表現",
   img:"404.png",
   desc:"いま おもっていることを、ノートに かきだして みるってのは、どう？",
   tags:{mood:["sad","angry","anxious"], energy:["low","mid"], social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"しんぱいをノートにかいてみる",
   g:"表現",
   img:"404.png",
   desc:"しんぱいなことを ぜんぶ かくと、あたまの なかが スッキリするよ。",
   tags:{mood:"anxious", energy:["low","mid"], social:"alone", body:["fine","heart"], wish:"nothing"}},
  {t:"えをかいてみる",
   g:"表現",
   img:"404.png",
   desc:"すきなものでも きもちでも、なんでも じゆうに えに してみよう。もし なにもおもいつかなかったら、わたしの すきなもの、かいてよ。 もぐら。",
   tags:{mood:["sad","anxious"], energy:"low", social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"みつけたものをえにかいてみる",
   g:"表現",
   img:"404.png",
   desc:"めのまえに あるものを じっくり みて、えに かいてみよう。",
   tags:{mood:["sad","happy"], energy:"mid", social:["alone","neutral"], body:"fine", wish:"nothing"}},
  {t:"だれかにおてがみをかいてみる",
   g:"表現",
   img:"404.png",
   desc:"だれかに おてがみを かいてみよう。きもちが つたわると いいね。",
   tags:{mood:"happy", energy:["high","mid"], social:"social", body:"fine", wish:"talk"}},
  {t:"ちいさなこえでうたってみる",
   g:"表現",
   img:"act-sing.png",
   desc:"ちいさな こえで、すきな うたを くちずさむ。きみだけの だいじな コンサート。",
   tags:{mood:["sad","anxious"], energy:"low", social:"alone", body:["fine","breath"], wish:"nothing"}},
  {t:"おおきなこえであくびしてみる",
   g:"表現",
   img:"act-sing.png",
   desc:"おもいきり おおきく あくびして、からだを ゆるめて みよう。",
   tags:{mood:"angry", energy:["high","mid"], social:"alone", body:"breath", wish:["nothing","play"]}},
  {t:"きもちをことばにしてみる",
   g:"表現",
   img:"404.png",
   desc:"「かなしい」とか 「つかれた」とか。いまの きもちを こえにだそう。",
   tags:{mood:["sad","anxious"], energy:["low","mid"], social:["alone","social"], body:["fine","bad"], wish:"talk"}},
  {t:"しんぱいをことばにしてみる",
   g:"表現",
   img:"404.png",
   desc:"なにが しんぱいか ことばで いってみるだけで、すこし らくに なるよ。",
   tags:{mood:"anxious", energy:["low","mid"], social:["alone","social"], body:["fine","heart"], wish:"talk"}},
  {t:"「かなしいな」ってつぶやいてみる",
   g:"表現",
   img:"404.png",
   desc:"「かなしいな」と ちいさく つぶやくだけで、かなしいきもちが ちょっとだけ おそとにいって くれるのさ。",
   tags:{mood:"sad", energy:"low", social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"「だいじょうぶ」ってつぶやいてみる",
   g:"表現",
   img:"404.png",
   desc:"「だいじょうぶ」って じぶんに いいきかせて みよう。だいじょうぶじゃなかったら、また もどってきてね。",
   tags:{mood:"anxious", energy:["low","mid"], social:"alone", body:["fine","heart"], wish:"nothing"}},
  {t:"「いまここにいる」ってかんじてみる",
   g:"表現",
   img:"404.png",
   desc:"いま、きみは なんていうところにいて だれといて、どんなふくをきて、だれとはなしてる？ かんがえてみて。",
   tags:{mood:"anxious", energy:["low","mid"], social:["alone","neutral"], body:"heart", wish:"nothing"}},
  {t:"100までかぞえてみる",
   g:"表現",
   img:"act-stand-mad.png",
   desc:"1から 100まで、ゆっくり こころのなかで かぞえて みよう。",
   tags:{mood:"angry", energy:["high","mid"], social:["alone","neutral"], body:["fine","heart"], wish:["nothing","play"]}},
  {t:"てのひらをぎゅっとひらいてみる",
   g:"表現",
   img:"404.png",
   desc:"てを ギュッと にぎって、パッと ひらくのを くりかえして みて。20かいぐらいまでは、おもしろい。30かいぐらい すると、なにしてるんだろうって おもう。100かいやると、てが つかれちゃった......。",
   tags:{mood:"angry", energy:["high","mid"], social:["alone","neutral"], body:"heart", wish:["nothing","play"]}},
  {t:"やりたいことをリストにかいてみる",
   g:"表現",
   img:"404.png",
   desc:"いま きみがやりたいことを リストに すると、たのしい きぶんに なっちゃうね。わたしはいま、おふとんで いっぱい ねたい。",
   tags:{mood:"happy", energy:["high","mid"], social:["alone","neutral"], body:"fine", wish:"play"}},
  {t:"きょうのことをにっきにかいてみる",
   g:"表現",
   img:"404.png",
   desc:"きょう あったことを にっきに かいてみよう。",
   tags:{mood:"happy", energy:["high","mid"], social:"alone", body:"fine", wish:["nothing","play"]}},
  {t:"きょうよかったことをひとつかんがえてみる",
   g:"表現",
   img:"404.png",
   desc:"きょう よかったことを、ひとつ おもいだして みるの。",
   tags:{mood:["sad","anxious"], energy:["low","mid"], social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"きょうよかったことを100こかんがえてみる!",
   g:"表現",
   img:"404.png",
   desc:"きょう よかったことを、100こ めざして おもいだす。",
   tags:{mood:"happy", energy:["high","mid"], social:["alone","neutral"], body:"fine", wish:["nothing","play"]}},
  {t:"ありがとうをつたえてみる",
   g:"表現",
   img:"404.png",
   desc:"だれかに「ありがとう」を つたえると、きみも あいても ハッピーせいじんに なるよ。",
   tags:{mood:"happy", energy:["high","mid"], social:"social", body:"fine", wish:"talk"}},
  {t:"すきなことにちょうせんしてみる",
   g:"表現",
   img:"404.png",
   desc:"すきな ことに、おもいきり ちょうせん してみようぜ！",
   tags:{mood:"happy", energy:"high", social:["alone","neutral"], body:"fine", wish:"play"}},
  {t:"おきにいりのものをながめてみる",
   g:"表現",
   img:"404.png",
   desc:"おきにいりの ものを、じっくり じーっと ながめて みよう。どこがすき？",
   tags:{mood:"sad", energy:"low", social:"alone", body:["fine","bad"], wish:"nothing"}},
  {t:"すきなものをあつめてみる",
   g:"表現",
   img:"404.png",
   desc:"ちかくにある じぶんの すきなものを あつめて ならべてみると、たのしい きぶんに なるんだぜ。",
   tags:{mood:"happy", energy:["high","mid"], social:"alone", body:"fine", wish:"play"}},
  {t:"たのしいことをかんがえてみる",
   g:"表現",
   img:"404.png",
   desc:"たのしい ことを、あたまの なかで いっぱい そうぞう してみよう！",
   tags:{mood:"happy", energy:["high","mid"], social:["alone","neutral"], body:"fine", wish:["nothing","play"]}},
  {t:"おもしろいかたちのくもをさがしてみる",
   g:"表現",
   img:"404.png",
   desc:"そらの くもの なかに、おもしろい かたちを みつけて みるのさ。あ、あれはマントヒヒ！",
   tags:{mood:"sad", energy:["low","mid"], social:["alone","neutral"], body:["fine","breath"], wish:"nothing"}},
];


/* ── きもちごとの見出し・説明・アイコン設定 ──
   mood の回答値（happy/sad/angry/anxious/neutral）ごとに設定する
   ============================================== */
const MD = {

  angry: {
    topImg:  "mad",
    ce_ikey: "mad",
    ct:      "もやもや",
    ttls: [
      "もやもやしてるんだね",
      "なんかイライラしているんだね",
      "むかーってなっているんだね",
    ],
    descs: [
      "なにかがうまくいかなくて、むかーっとしちゃうこと、だれにでもあるよ。そのエネルギーをそとにだしてあげよう。",
      "イライラしてるきもち、ちゃんとわかるよ。そういうときはからだをうごかすとすっきりするよ！",
      "もやもやしてるとき、むりにわらわなくていいよ。すこしずつきもちをだしてみよう。",
    ],
  },

  sad: {
    topImg:  "cry",
    ce_ikey: "cry",
    ct:      "かなしい",
    ttls: [
      "かなしいきもちなんだね",
      "なんかかなしくなっちゃったんだね",
      "しんどいきもちなんだね",
    ],
    descs: [
      "なみだがでそうなくらいかなしいこと、あるよね。そのきもちはそのままでいいよ。ゆっくりしてね。",
      "かなしいとき、むりにがんばらなくていいよ。じぶんのきもちをたいせつにしてね。",
      "しんどいきもち、ひとりでかかえなくていいよ。だれかそばにいるよ。",
    ],
  },

  anxious: {
    topImg:  "puzzled",
    ce_ikey: "puzzled",
    ct:      "しんぱい",
    ttls: [
      "なんだかドキドキしてるんだね",
      "しんぱいなきもちなんだね",
      "こころがざわざわしてるんだね",
    ],
    descs: [
      "しんぱいなことやこわいことがあると、からだもどきどきしちゃうよね。ひとつずつ、ゆっくりいこうね。",
      "ざわざわするきもち、ちゃんとわかるよ。いっしょにおちつこうね。",
      "どきどきしてるとき、ひとりでかかえなくていいよ。そばにいるよ。",
    ],
  },

  happy: {
    topImg:  "smile",
    ce_ikey: "smile",
    ct:      "たのしい",
    ttls: [
      "たのしいきもちなんだね！",
      "うれしいきもちなんだね！",
      "わくわくしてるんだね！",
    ],
    descs: [
      "わあ、うれしいな！そのきもち、だいじにしてね。たのしいエネルギーをいっぱいつかってみよう！",
      "たのしいきもちはまわりのひともうれしくさせるよ。とってもすてき！",
      "わくわくしてるって、すてきだね！そのきもちをいっぱいたのしんでね！",
    ],
  },

  neutral: {
    topImg:  "normal",
    ce_ikey: "normal",
    ct:      "ふつう",
    ttls: [
      "なんとなくそんなきもちなんだね",
      "ぼんやりしてるかんじなんだね",
      "まあまあなきもちなんだね",
    ],
    descs: [
      "おおきなきもちはないけど、なんとなくぼんやりしてたり、つかれてたりするのかもね。ゆっくりしてね。",
      "ふつうのときも、じぶんのきもちをきいてあげるのはたいせつなことだよ。",
      "まあまあなきもちのとき、なにかひとつちいさなことをやってみると、きもちがかわるかも。",
    ],
  },

};